version: 0.2

phases:
  install:
    runtime-versions:
    # which application to be installed, that is docker and nodejs
      docker: 18
      nodejs: 12

  pre_build:
    commands:
      - echo Installing Node.js...
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -y nodejs
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION) # Login to Amazon ECR

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t ebs-deploy-demo:latest . # Build Docker image
      - docker push ebs-deploy-demo:latest  # Push Docker image to ECR

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files: []
