version: 0.2

phases:
  install:
    runtime-versions:
    # which application to be installed, that is docker and nodejs
      
      nodejs: 18

  pre_build:
    commands:
      - echo Installing Node.js...
      - curl -sL https://deb.nodesource.com/setup_18.x | bash -
      - apt-get install -y nodejs
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 798304154621.dkr.ecr.us-east-1.amazonaws.com/ebs-deploy-demo # Login to Amazon ECR

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 798304154621.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t ebs-deploy-demo .
      - aws ecr batch-delete-image --repository-name ebs-deploy-demo --image-ids imageTag=latest
      - docker tag ebs-deploy-demo:latest 798304154621.dkr.ecr.us-east-1.amazonaws.com/ebs-deploy-demo:latest
      - docker push 798304154621.dkr.ecr.us-east-1.amazonaws.com/ebs-deploy-demo:latest
    
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files: []